# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  - board: xiao_ble
    shield: space_mouse
#    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME="SuperSM"
#  - board: promicro_nrf52840/nrf52840/uf2
#    shield: space_mouse
#    artifact-name: space_mouse_promicro
#    snippet: zmk-usb-logging
  - board: nice_nano
    shield: space_mouse
#    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME="NanoSM"
